# Generated by Django 4.2.3 on 2023-08-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
